// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7ppIWJU7L75QsrykeQlLH20P8neLfch4',
    appId: '1:968737222181:web:917a9fce025b0791b699cc',
    messagingSenderId: '968737222181',
    projectId: 'kharchaai-e46a1',
    authDomain: 'kharchaai-e46a1.firebaseapp.com',
    storageBucket: 'kharchaai-e46a1.firebasestorage.app',
    measurementId: 'G-PDWHN15QVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlwr1UqWTY3l41zyfs-2UjT1Z7bpBMvZs',
    appId: '1:968737222181:android:1b79087f6a7d7445b699cc',
    messagingSenderId: '968737222181',
    projectId: 'kharchaai-e46a1',
    storageBucket: 'kharchaai-e46a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC66HrpJKygek77VD5a_O4Keu72AOHlPrM',
    appId: '1:968737222181:ios:f8546ae54db6c32db699cc',
    messagingSenderId: '968737222181',
    projectId: 'kharchaai-e46a1',
    storageBucket: 'kharchaai-e46a1.firebasestorage.app',
    iosBundleId: 'com.kharchaai.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC66HrpJKygek77VD5a_O4Keu72AOHlPrM',
    appId: '1:968737222181:ios:f8546ae54db6c32db699cc',
    messagingSenderId: '968737222181',
    projectId: 'kharchaai-e46a1',
    storageBucket: 'kharchaai-e46a1.firebasestorage.app',
    iosBundleId: 'com.kharchaai.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7ppIWJU7L75QsrykeQlLH20P8neLfch4',
    appId: '1:968737222181:web:6444e65ef9fb74adb699cc',
    messagingSenderId: '968737222181',
    projectId: 'kharchaai-e46a1',
    authDomain: 'kharchaai-e46a1.firebaseapp.com',
    storageBucket: 'kharchaai-e46a1.firebasestorage.app',
    measurementId: 'G-NC0KZHG1K3',
  );

}